name: appmap-analysis

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

permissions:
  # Read the baseline artifact in order to perform the AppMap comparison.
  actions: read
  # Commit the AppMap configuration.
  # If the EndBug/add-and-commit is removed, this can be changed to 'read'.
  contents: write
  # Add check annotations to the source code when a problem is detected.
  checks: write
  # Add a comment to the pull request.
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install AppMap tools
        id: install-appmap
        uses: getappmap/install-action@v1
        with:
          tools-url: "https://github.com/getappmap/appmap-js/releases/download/%40appland%2Fappmap%40summary-report/appmap-linux-x64"
          install-appmap-library: false

      - name: Run tests
        run: bundle exec rails test

      - name: Archive AppMaps
        if: github.event_name != 'pull_request'
        uses: getappmap/archive-action@feat/summary-report
        with:
          directory: ${{ inputs.directory }}

      - name: Analyze AppMaps
        uses: getappmap/analyze-action@feat/summary-report
        if: github.event_name == 'pull_request'
        with:
          directory: ${{ inputs.directory }}
          base-revision: ${{ github.event.pull_request.base.sha }}
          head-revision: ${{ github.event.pull_request.head.sha }}
          project-summary: true
